### ISSUE TITLE
Suggestion: Add support for Laravel Sail + WSL2

### ISSUE THREAD

**Issue by zunnur-trinovik** [joschuba/statamic-vite#2]
Hi, Unless the following config is added, hot reload will not work in WSL2. Alternatively, Put as comment in vite.config.js so the user can uncomment if necessary.

**vite.config.js:**
```
server: {
    hmr: {
          host: 'localhost',
    },
}
```
**docker-compose.yml**
```
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
networks:
    sail:
        driver: bridge
```
